Auth/urls.py
from django.urls import path

from . import views

app_name = 'auth'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup', views.signup_view, name='signup'),
    path('login', views.login_view, name='login'),

    path('logout', views.logout_view, name='logout'),
    path('members', views.members_view, name='members'),
    path('profile/<int:user_id>/', views.profile_view, name='profile'),
    path('edit_profile/<int:user_id>/', views.edit_profile, name='edit_profile'),
]

FB_Replica/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.urls import re_path
from django.views.static import serve


urlpatterns = [
    path('', include('Auth.urls')),
    path('timeline/', include('timeline.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

timeline/urls.py
from django.urls import path

from . import views

app_name = 'timeline'

urlpatterns = [
    path('wall_post', views.wall_post_view, name='wall_post'),
    path('comment_post/<int:post_id>/', views.comment_post_view, name='comment_post'),
    path('like_post/<int:post_id>/', views.like_post_view, name='like_post'),
    path('unlike_post/<int:post_id>/', views.unlike_post_view, name='unlike_post'),
    path('like_comment/<int:comment_id>/', views.like_comment_view, name='like_comment'),
    path('unlike_comment/<int:comment_id>/', views.unlike_comment_view, name='unlike_comment'),
]

templates/base.html
{% if user.is_anonymous %}
    {% include "login.html" %}
{% else %}
{% load static %}
{% load tags %}

{% url 'auth:index' as home %}
{% url 'auth:members' as members%}
{% url 'auth:profile' user.pk as my_profile %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Dobble Social Network</title>
    <link href="{% static 'css/wall-post.css' %}" rel="stylesheet">
      <link href="{% static 'css/profile.css' %}" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.0/css/all.min.css" integrity="sha512-gRH0EcIcYBFkQTnbpO8k0WlsD20x5VzjhOA1Og8+ZUAhcMUCvd+APD35FJw3GzHAP3e+mP28YcDJxVr745loHw==" crossorigin="anonymous" />

  </head>

  <body class="base-body">

{#  <header>#}
{#    <div class="container">#}
{#      <img src="{% static 'img/logo.png' %}" class="logo" alt="">#}
{#        {% if user.is_anonymous %}#}
{#          <form class="form-inline" method='POST' action='{% url "auth:login" %}'>#}
{#            {% csrf_token %}#}
{#            <div class="form-group">#}
{#              <label class="sr-only" for="exampleInputEmail3">Email address</label>#}
{#              <input type="email" class="form-control" id="exampleInputEmail3" name="email" placeholder="Enter email">#}
{#            </div>#}
{#            <div class="form-group">#}
{#              <label class="sr-only" for="exampleInputPassword3">Password</label>#}
{#              <input type="password" class="form-control" id="exampleInputPassword3" name="password" placeholder="Password">#}
{#            </div>#}
{#            <button type="submit" class="btn btn-default">Sign in</button><br>#}
{#            <div class="checkbox">#}
{#              <label>#}
{#                <input type="checkbox"> Remember me#}
{#              </label>#}
{#            </div>#}
{#          </form>#}
{#        {% else %}#}
{#            <form class='form-inline' method='POST' action='{% url "auth:logout" %}'>#}
{#                {% csrf_token %}#}
{#                <button class='btn btn-default' type='submit'>Logout</button><br>#}
{#            </form>#}
{#        {% endif %}#}
{#    </div>#}
{#  </header>#}

    {% if not user.is_anonymous %}
    <nav class="navbar navbar-default" id="nav-1">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="{% active request home  %}" id="nav__list__items" ><a href="{{ home }}"><i class="fas fa-home"></i></a></li>
            <li class="{% active request members %}" id="nav__list__items"  ><a href="{{ members }}"><i class="fas fa-user-friends"></i></a></li>
            <li id="nav__list__items" ><a href="#"><i class="fas fa-phone"></i></a></li>
            <li id="nav__list__items" > <a href="#"><i class="fas fa-users"></i></a></li>
            <li id="nav__list__items" ><a href="#"><i class="far fa-image"></i></a></li>
            <li class="{% active request my_profile%}" id="nav__list__items" ><a href="{{ my_profile }}"><i class="fas fa-user-circle"></i></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    {% else %}
        <br>
    {% endif %}

    {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error{% else %}{{ message.tags|title }}{% endif %}!</strong> {{ message }}
      </div>
      {% endfor %}
    {% endif %}

    <section>
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            {% block content %}
            {% endblock %}
          </div>
          <div class="col-md-4">
{#            {% if user.is_anonymous %}#}
{#                <form class="form" method='POST' action='{% url "auth:signup" %}'>#}
{#                    {% csrf_token %}#}
{#                    <div class="form-group">#}
{#                      <label class="sr-only" for="first_name">First Name</label>#}
{#                      <input class="form-control" id="first_name" type="text" name="first_name" placeholder="First Name" required>#}
{#                    </div>#}
{#                    <div class="form-group">#}
{#                      <label class="sr-only" for="last_name">Last Name</label>#}
{#                      <input class="form-control" id="last_name" type="text" name="last_name" placeholder="Last Name" required>#}
{#                    </div>#}
{#                    <div class="form-group">#}
{#                      <label class="sr-only" for="email">Email address</label>#}
{#                      <input class="form-control" id="email" type="email" name="email" placeholder="Enter email" required>#}
{#                    </div>#}
{#                    <div class="form-group">#}
{#                      <label class="sr-only" for="password">Password</label>#}
{#                      <input class="form-control" id="password" type="password" name="password" placeholder="Password" required>#}
{#                    </div>#}
{#                    <div class="form-group">#}
{#                      <label class="sr-only" for="c_password">Confirm Password</label>#}
{#                      <input type="password" class="form-control" id="c_password" placeholder="Confirm Password" oninput="check(this)" >#}
{#                    </div>#}
{#                    <script language='javascript' type='text/javascript'>#}
{#                        function check(input) {#}
{#                            if (input.value != document.getElementById('password').value) {#}
{#                                input.setCustomValidity('Password and Confirm Password do not match.');#}
{#                            } else {#}
{#                                // input is valid -- reset the error message#}
{#                                input.setCustomValidity('');#}
{#                            }#}
{#                        }#}
{#                    </script>#}
{#                    <br /><br />#}
{#                    <button type="submit" class="btn btn-default">Register</button><br>#}
{#                </form>#}
{##}
{#            {% else %}#}
                <div class="panel panel-default friends" id="friend-pnl">
            <div class="panel-heading">
            <h3 class="panel-title">My Friends</h3>
            </div>
            <div class="panel-body">
            <ul>
              <li><a href="profile.html" class="thumbnail"><img src="{% static 'img/download.jpeg' %}" alt=""></a></li>
              <li><a href="profile.html" class="thumbnail"><img src="{% static 'img/download.jpeg' %}" alt=""></a></li>
              <li><a href="profile.html" class="thumbnail"><img src="{% static 'img/download.jpeg' %}" alt=""></a></li>
              <li><a href="profile.html" class="thumbnail"><img src="{% static 'img/download.jpeg' %}" alt=""></a></li>
              <li><a href="profile.html" class="thumbnail"><img src="{% static 'img/download.jpeg' %}" alt=""></a></li>
              <li><a href="profile.html" class="thumbnail"><img src="{% static 'img/download.jpeg' %}" alt=""></a></li>
              <li><a href="profile.html" class="thumbnail"><img src="{% static 'img/download.jpeg' %}" alt=""></a></li>
              <li><a href="profile.html" class="thumbnail"><img src="{% static 'img/download.jpeg' %}" alt=""></a></li>
              <li><a href="profile.html" class="thumbnail"><img src="{% static 'img/download.jpeg' %}" alt=""></a></li>
            </ul>
            <div class="clearfix"></div>
            <a class="btn btn-primary" href="#" id="view-btn">View All Friends</a>
            </div>
            </div>
                <div class="panel panel-default groups">
            <div class="panel-heading">
            <h3 class="panel-title">Latest Groups</h3>
            </div>
            <div class="panel-body">
            <div class="group-item">
              <img src="{% static 'img/group.png' %}" alt="">
              <h4><a href="#" class="sample">Sample Group One</a></h4>
              <p>This is a paragraph of intro text, or whatever I want to call it.</p>
            </div>
            <div class="clearfix"></div>
            <div class="group-item">
              <img src="{% static 'img/group.png' %}" alt="">
              <h4><a href="#" class="sample">Sample Group Two</a></h4>
              <p>This is a paragraph of intro text, or whatever I want to call it.</p>
            </div>
            <div class="clearfix"></div>
            <div class="group-item">
              <img src="{% static 'img/group.png' %}" alt="">
              <h4><a href="#" class="sample">Sample Group Three</a></h4>
              <p>This is a paragraph of intro text, or whatever I want to call it.</p>
            </div>
            <div class="clearfix"></div>
            <a href="#" class="btn btn-primary" id="view-btn-1">View All Groups</a>
            </div>
            </div>
{#            {% endif %}#}

          </div>
        </div>
      </div>
    </section>

{#    <footer>#}
{#      <div class="container">#}
{#        <p>Dobble Copyright &copy, 2015</p>#}
{#      </div>#}
{#    </footer>#}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
  </body>
</html>


<script type="text/javascript">

    function change_profile_pix() {
        document.getElementById('profile_image').click();
    }

    function get_images() {
        document.getElementById('images').click();
    }

    function get_videos() {
        document.getElementById('videos').click();
    }

    function get_files() {
        document.getElementById('files').click();
    }

{#    document.getElementById('get_files').onclick = function() {#}
{#        document.getElementById('files').click();#}
{#    };#}
{#    document.getElementById('get_images').onclick = function() {#}
{#        document.getElementById('images').click();#}
{#    };#}
{#    document.getElementById('').onclick = function() {#}
{#        document.getElementById('').click();#}
{#    };#}

</script>
{% endif %}

templates/base_index.html
{% load static %}
{% load tags %}

{% url 'auth:index' as home %}
{% url 'auth:members' as members%}
{% url 'auth:profile' user.pk as my_profile %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Dobble Social Network</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
  </head>

  <body>

  <header>
    <div class="container">
      <img src="{% static 'img/logo.png' %}" class="logo" alt="">
        {% if user.is_anonymous %}
          <form class="form-inline" method='POST' action='{% url "auth:login" %}'>
            {% csrf_token %}
            <div class="form-group">
              <label class="sr-only" for="exampleInputEmail3">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail3" name="email" placeholder="Enter email">
            </div>
            <div class="form-group">
              <label class="sr-only" for="exampleInputPassword3">Password</label>
              <input type="password" class="form-control" id="exampleInputPassword3" name="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-default">Sign in</button><br>
{#            <div class="checkbox">#}
{#              <label>#}
{#                <input type="checkbox"> Remember me#}
{#              </label>#}
{#            </div>#}
          </form>
        {% else %}
            <form class='form-inline' method='POST' action='{% url "auth:logout" %}'>
                {% csrf_token %}
                <button class='btn btn-default' type='submit'>Logout</button><br>
            </form>
        {% endif %}
    </div>
  </header>

    {% if not user.is_anonymous %}
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="{% active request home %}" ><a href="{{ home }}">Home</a></li>
            <li class="{% active request members %}" ><a href="{{ members }}">Members</a></li>
            <li><a href="#">Contact</a></li>
            <li><a href="#">Groups</a></li>
            <li><a href="#">Photos</a></li>
            <li class="{% active request my_profile%}" ><a href="{{ my_profile }}">Profile</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    {% else %}
        <br>
    {% endif %}

    {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error{% else %}{{ message.tags|title }}{% endif %}!</strong> {{ message }}
      </div>
      {% endfor %}
    {% endif %}

    <section>
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            {% block content %}
            {% endblock %}
          </div>
          <div class="col-md-4">
            {% if user.is_anonymous %}
                <form class="form" method='POST' action='{% url "auth:signup" %}'>
                    {% csrf_token %}
                    <div class="form-group">
                      <label class="sr-only" for="first_name">First Name</label>
                      <input class="form-control" id="first_name" type="text" name="first_name" placeholder="First Name" required>
                    </div>
                    <div class="form-group">
                      <label class="sr-only" for="last_name">Last Name</label>
                      <input class="form-control" id="last_name" type="text" name="last_name" placeholder="Last Name" required>
                    </div>
                    <div class="form-group">
                      <label class="sr-only" for="email">Email address</label>
                      <input class="form-control" id="email" type="email" name="email" placeholder="Enter email" required>
                    </div>
                    <div class="form-group">
                      <label class="sr-only" for="password">Password</label>
                      <input class="form-control" id="password" type="password" name="password" placeholder="Password" required>
                    </div>
                    <div class="form-group">
                      <label class="sr-only" for="c_password">Confirm Password</label>
                      <input type="password" class="form-control" id="c_password" placeholder="Confirm Password" oninput="check(this)" >
                    </div>
                    <script language='javascript' type='text/javascript'>
                        function check(input) {
                            if (input.value != document.getElementById('password').value) {
                                input.setCustomValidity('Password and Confirm Password do not match.');
                            } else {
                                // input is valid -- reset the error message
                                input.setCustomValidity('');
                            }
                        }
                    </script>
                    <br /><br />
                    <button type="submit" class="btn btn-default">Register</button><br>
                </form>

            {% else %}
                <div class="panel panel-default friends">
            <div class="panel-heading">
            <h3 class="panel-title">My Friends</h3>
            </div>
            <div class="panel-body">
            <ul>
              <li><a href="profile.html" class="thumbnail"><img src="{% static 'img/user.png' %}" alt=""></a></li>
              <li><a href="profile.html" class="thumbnail"><img src="{% static 'img/user.png' %}" alt=""></a></li>
              <li><a href="profile.html" class="thumbnail"><img src="{% static 'img/user.png' %}" alt=""></a></li>
              <li><a href="profile.html" class="thumbnail"><img src="{% static 'img/user.png' %}" alt=""></a></li>
              <li><a href="profile.html" class="thumbnail"><img src="{% static 'img/user.png' %}" alt=""></a></li>
              <li><a href="profile.html" class="thumbnail"><img src="{% static 'img/user.png' %}" alt=""></a></li>
              <li><a href="profile.html" class="thumbnail"><img src="{% static 'img/user.png' %}" alt=""></a></li>
              <li><a href="profile.html" class="thumbnail"><img src="{% static 'img/user.png' %}" alt=""></a></li>
              <li><a href="profile.html" class="thumbnail"><img src="{% static 'img/user.png' %}" alt=""></a></li>
            </ul>
            <div class="clearfix"></div>
            <a class="btn btn-primary" href="#">View All Friends</a>
            </div>
            </div>
                <div class="panel panel-default groups">
            <div class="panel-heading">
            <h3 class="panel-title">Latest Groups</h3>
            </div>
            <div class="panel-body">
            <div class="group-item">
              <img src="{% static 'img/group.png' %}" alt="">
              <h4><a href="#" class="">Sample Group One</a></h4>
              <p>This is a paragraph of intro text, or whatever I want to call it.</p>
            </div>
            <div class="clearfix"></div>
            <div class="group-item">
              <img src="{% static 'img/group.png' %}" alt="">
              <h4><a href="#" class="">Sample Group Two</a></h4>
              <p>This is a paragraph of intro text, or whatever I want to call it.</p>
            </div>
            <div class="clearfix"></div>
            <div class="group-item">
              <img src="{% static 'img/group.png' %}" alt="">
              <h4><a href="#" class="">Sample Group Three</a></h4>
              <p>This is a paragraph of intro text, or whatever I want to call it.</p>
            </div>
            <div class="clearfix"></div>
            <a href="#" class="btn btn-primary">View All Groups</a>
            </div>
            </div>
            {% endif %}

          </div>
        </div>
      </div>
    </section>

    <footer>
      <div class="container">
        <p>Dobble Copyright &copy, 2015</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
  </body>
</html>


<script type="text/javascript">

    function change_profile_pix() {
        document.getElementById('profile_image').click();
    }

    function get_images() {
        document.getElementById('images').click();
    }

    function get_videos() {
        document.getElementById('videos').click();
    }

    function get_files() {
        document.getElementById('files').click();
    }

{#    document.getElementById('get_files').onclick = function() {#}
{#        document.getElementById('files').click();#}
{#    };#}
{#    document.getElementById('get_images').onclick = function() {#}
{#        document.getElementById('images').click();#}
{#    };#}
{#    document.getElementById('').onclick = function() {#}
{#        document.getElementById('').click();#}
{#    };#}

</script>

templates/comment_post.html
<div class="comment-form">
   <form class="form-inline" method='POST' action='{% url "timeline:comment_post" post.id %}'>
    {% csrf_token %}
    <div class="form-group">
      <input type="text" class="form-control" name="description" placeholder="enter comment">
    </div>
    <button type="submit" class="btn btn-default" id="add-btn">Add</button>
  </form>
</div>
<div class="clearfix"></div>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if not user.is_anonymous %}
        {% include "wall_post.html" %}
        {% for post in posts_list %}
          <div class="panel panel-default post" id="post-bg">
          <div class="panel-body" id="post-1">
             <div class="row">
               <div class="col-sm-2" id="post-2">
                 <a href="{% url 'auth:profile' post.user.pk %}" class="post-avatar"><img style="border-radius: 100%;max-width: 100%;height: auto;" src="{{ post.user.profile.image.url }}" alt="{{ post.user.get_full_name }}"></a>
               </div>
               <div class="col-sm-10">
                 <div class="bubble">
                   <div class="pointer">
                     <p>{{ post.description }}</p><br>
                     {% for image in post.images.all %}
                       <br><img style="border-radius: 10px;max-width: 100%;height: auto;" src="{{ image.image.url }}" alt="">
                     {% endfor %}
                     {% for file in post.files.all %}
                        <br><a href="{{ file.file.url }}">{{ file.file_name }}</a>
                     {% endfor %}
                   </div>
                   <div class="pointer-border"></div>
                 </div>

                 {% if post.can_like %}
                     <p class="post-actions"><a class="like-1" href="{% url "timeline:like_post" post.id %}">Like</a>&nbsp;&nbsp;&nbsp;&nbsp; {{ post.likes_count}} {{ post.likes_count | pluralize:"Like,Likes" }}</p>
                 {% else %}
                     <p class="post-actions"><a href="{% url "timeline:unlike_post" post.id %}">unlike</a>&nbsp;&nbsp;&nbsp;&nbsp;{{ post.likes_count}} {{ post.likes_count | pluralize:"Like,Likes" }}</p>
                 {% endif %}

                 {% include "comment_post.html" %}

                 <div class="comments">
                   {% for comment in post.comments %}
                     <div class="comment">

                 <table>
                    <tbody>
                        <tr>
                            <td rowspan="2" colspan="2"><a href="{% url 'auth:profile' comment.user.pk %}" class="comment-avatar pull-left"><img style="border-radius: 100%;max-width: 100%;height: auto;" src="{{ comment.user.profile.image.url }}" alt=""></a></td>
                            <td>
                                <div class="comment-text">
                                    <p>{{ comment.description }}</p>
                                  </div>
                              </td>
                        </tr>
                        <tr>
                            <td>
                                {% if comment.can_like %}
                                  <p class="post-actions"><a href="{% url "timeline:like_comment" comment.id %}">Like</a>&nbsp;&nbsp;&nbsp;&nbsp;
                                    {{ comment.likes_count}} {{ comment.likes_count | pluralize:"Like,Likes" }}</p>
                                {% else %}
                                  <p class="post-actions"><a href="{% url "timeline:unlike_comment" comment.id %}">unlike</a>&nbsp;&nbsp;&nbsp;&nbsp;
                                    {{ comment.likes_count}} {{ comment.likes_count | pluralize:"Like,Likes" }}</p>
                                {% endif %}
                            </td>
                        </tr>
                    </tbody>
                </table>

                     </div>
                     <div class="clearfix"></div>
                   {% endfor %}
                 </div>
               </div>
             </div>
          </div>
        </div>
        {% endfor %}
    {% endif %}

{% endblock %}

templates/members.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% if not user.is_anonymous %}
        <div class="members">
            <h1 class="page-header">Members</h1>
            <div class="row member-row">
            {% for member in members_list %}
                <div class="col-md-3">
                  <a href="{% url 'auth:profile' member.pk %}"><img src="{{ member.profile.image.url }}" style="border-radius: 100%;max-width: 100%;height: 100%;" class="img-thumbnail" alt=""></a>
                  <div class="text-center">
                    {{ member.get_full_name }}
                  </div>
                </div>
            {% endfor %}
          </div>
        </div>
    {% endif %}

{% endblock %}

templates/posts_list.html
{% for post in posts_list %}
  <div class="panel panel-default post">
  <div class="panel-body">
     <div class="row">
       <div class="col-sm-2">
         <a href="{% url 'auth:profile' post.user.pk %}" class="post-avatar"><img style="border-radius: 100%;max-width: 100%;height: 100%;" src="{{ post.user.profile.image.url }}" alt="{{ post.user.get_full_name }}"></a>
       </div>
       <div class="col-sm-10">
         <div class="bubble">
           <div class="pointer">
             <p>{{ post.description }}</p><br>
             {% for image in post.images.all %}
               <br><img style="border-radius: 10px;max-width: 100%;height: 100%;" src="{{ image.image.url }}" alt="">
             {% endfor %}
             {% for file in post.files.all %}
                <br><a href="{{ file.file.url }}">{{ file.file_name }}</a>
             {% endfor %}
           </div>
           <div class="pointer-border"></div>
         </div>

         {% if post.can_like %}
             <p class="post-actions"><a href="{% url "timeline:like_post" post.id %}">Like</a>&nbsp;&nbsp;&nbsp;&nbsp; {{ post.likes_count}} {{ post.likes_count | pluralize:"Like,Likes" }}</p>
         {% else %}
             <p class="post-actions"><a href="{% url "timeline:unlike_post" post.id %}">unlike</a>&nbsp;&nbsp;&nbsp;&nbsp;{{ post.likes_count}} {{ post.likes_count | pluralize:"Like,Likes" }}</p>
         {% endif %}

         {% include "comment_post.html" %}

         <div class="comments">
           {% for comment in post.comments %}
             <div class="comment">

         <table>
            <tbody>
                <tr>
                    <td rowspan="2" colspan="2"><a href="{% url 'auth:profile' comment.user.pk %}" class="comment-avatar pull-left"><img style="border-radius: 100%;max-width: 100%;height: 100%;" src="{{ comment.user.profile.image.url }}" alt=""></a></td>
                    <td>
                        <div class="comment-text">
                            <p>{{ comment.description }}</p>
                          </div>
                      </td>
                </tr>
                <tr>
                    <td>
                        {% if comment.can_like %}
                          <p class="post-actions"><a href="{% url "timeline:like_comment" comment.id %}">Like</a>&nbsp;&nbsp;&nbsp;&nbsp;
                            {{ comment.likes_count}} {{ comment.likes_count | pluralize:"Like,Likes" }}</p>
                        {% else %}
                          <p class="post-actions"><a href="{% url "timeline:unlike_comment" comment.id %}">unlike</a>&nbsp;&nbsp;&nbsp;&nbsp;
                            {{ comment.likes_count}} {{ comment.likes_count | pluralize:"Like,Likes" }}</p>
                        {% endif %}
                    </td>
                </tr>
            </tbody>
        </table>

             </div>
             <div class="clearfix"></div>
           {% endfor %}
         </div>
       </div>
     </div>
  </div>
</div>
{% endfor %}